### ISSUE TITLE
バグ報告

### ISSUE THREAD

**Issue by Bekosantux** [BulletProject/MiRm-Terms#1]
10人規模の鯖民なのですがアプデしてから鯖主鯖民関係なく全く移動ができないようになった人がいました。私は問題ないのですが動けない人はエンパかtp、ボートくらいしか移動手段がないそうです。ある人はマイクラを再インストールしても直らなかったそうなので、本体の問題ではなさそうです。

**Comment by haniokasai** [comment]
ログインは適切になされているか確認できますか。

**Comment by Bekosantux** [comment]
ログインフォームも出てこないそうです。

**Comment by haniokasai** [comment]
なるほど、了解しました。
修正しますね。

**Comment by haniokasai** [comment]
修正されたと思います
